Test msw
ssementsov/itechlib pull request #10
Opened 2021-12-06 15:33 UTC by LubavaZ

2021-12-06 20:07 UTC, SilCorp requested changes

2021-12-06 20:07 UTC, SilCorp commented on src/pages/book/[id].js
> +          <Button
It is better to use custom ButtonLink component

2021-12-06 20:07 UTC, SilCorp commented on src/pages/book/[id].js
> +  const res = await fetch(`https://my.backend/books/${params.id}`)
Use the path to the endpoint from the environment variable

2021-12-07 07:59 UTC, LubavaZ commented on src/pages/book/[id].js
> +          <Button
This "Link" from Next - I need it for routing. And I put component="a" prop for Button, so a browser sees it like a link. That's why it is ok, I guess

2021-12-07 10:00 UTC, SilCorp approved these changes

2021-12-07 10:00 UTC, merged